### PR TITLE
0.4.5

### PR DESCRIPTION
**Pull request by st3107**
Release 0.4.5

https://github.com/xpdAcq/xpdConf/releases/tag/0.4.5

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
changes look good.  Do we know why the feedstock is not building?

**Comment by st3107** [comment]
@sbillinge This is because the databroker 2.0.0a needs the `tile` package. The `tile` packages has dependencies issues and the issues cause the failure of the import from databroker.

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/xpdconf_1658339377036/test_tmp/run_test.py", line 5, in <module>
    import xpdconf.conf
  File "/home/conda/feedstock_root/build_artifacts/xpdconf_1658339377036/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/xpdconf/conf.py", line 159, in <module>
    glbl_dict["exp_db"] = databroker.v2.temp()
  File "/home/conda/feedstock_root/build_artifacts/xpdconf_1658339377036/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/databroker/v2.py", line 17, in temp
    from .mongo_normalized import Catalog
  File "/home/conda/feedstock_root/build_artifacts/xpdconf_1658339377036/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/databroker/mongo_normalized.py", line 24, in <module>
    from tiled.adapters.xarray import DatasetAdapter
  File "/home/conda/feedstock_root/build_artifacts/xpdconf_1658339377036/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/tiled/adapters/xarray.py", line 7, in <module>
    from ..adapters.array import ArrayAdapter
  File "/home/conda/feedstock_root/build_artifacts/xpdconf_1658339377036/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/tiled/adapters/array.py", line 3, in <module>
    from ..server.object_cache import get_object_cache
  File "/home/conda/feedstock_root/build_artifacts/xpdconf_1658339377036/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/tiled/server/object_cache.py", line 13, in <module>
    import cachey
ModuleNotFoundError: No module named 'cachey'
```

**Comment by st3107** [comment]
I suggest we wait for the DSSI group to fix conda recipe of tile and then trigger the build again. It is not good to add dependencies on our side.

**Comment by st3107** [comment]
Wait for a fix of the tiled recipe.

**Pull request closed without merging**
